sudo: false
language: python
python:
  - "3.7"
install:
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update
script:
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "58fa5526451a"
  - COMMIT_AUTHOR_EMAIL: "authors@sanitizer.spec.invalid"
